import plugin from '../../lib/plugins/plugin.js'
import fetch, { File, FormData } from 'node-fetch'
import fs from 'fs'
import path from 'node:path'
import { createHash } from 'node:crypto'
import _ from 'lodash'

if (!global.segment) {
  global.segment = (await import('oicq')).segment
}
const baseUrl = 'https://meme-generatoe-sha.onrender.com'
/**
 * 机器人发表情是否引用回复用户
 * @type {boolean}
 */
const reply = true
/**
 * 是否强制使用#触发命令
 */
const forceSharp = false
/**
 * 主人保护，撅主人时会被反撅 (暂时只支持QQ)
 * @type {boolean}
 */
const masterProtectDo = true
/**
 * 用户输入的图片，最大支持的文件大小，单位为MB
 * @type {number}
 */
const maxFileSize = 10

const memeDataDir = 'data/memes'
const listPageSize = Math.min(300, Math.max(50, Number.parseInt(process.env.MEME_LIST_PAGE_SIZE || '200', 10) || 200))
const listCacheVersion = 4
const minimumImageBytes = 512
/**
 * 优先使用服务端构建镜像时预渲染好的静态列表（/memes/static/list/manifest.json）。
 * 静态列表的 meme 集合与本页大小和本地不一致时自动回退到实时渲染接口。
 * @type {boolean}
 */
const staticListEnabled = true
const staticListManifestTimeout = 15000
const staticListImageTimeout = 60000

let keyMap = {}

let infos = {}

/**
 * 主人保护list 如['lash','do','beat_up','little_do']
 */
let protectList = ['lash', 'do', 'beat_up', 'little_do']

/**
 * 本地兼容的常见关键词写法，不修改服务端元数据。
 */
const randomMemeAliases = {
  '咖波锤打': '咖波捶打'
}

const commandRules = [
  {
    reg: '^(#)?(meme(s)?|表情包)列表(?:\\s*(\\d+))?$',
    fnc: 'memesList'
  },
  {
    reg: '^#?随机\\s*(meme(s)?|表情包)\\s*$',
    fnc: 'randomMemes'
  },
  {
    reg: '^#?随机\\s*(meme(s)?|表情包)\\s+.+$',
    fnc: 'randomMeme'
  },
  {
    reg: '^#?(meme(s)?|表情包)帮助',
    fnc: 'memesHelp'
  },
  {
    reg: '^#?(meme(s)?|表情包)搜索',
    fnc: 'memesSearch'
  },
  {
    reg: '^#?(meme(s)?|表情包)更新',
    fnc: 'memesUpdate'
  }
]

const listRenderTasks = new Map()

export class memes extends plugin {
  constructor() {
    let option = {
      /** 功能名称 */
      name: '表情包',
      /** 功能描述 */
      dsc: '表情包制作',
      /** https://oicqjs.github.io/oicq/#events */
      event: 'message',
      /** 优先级，数字越小等级越高 */
      priority: 5000,
      rule: [...commandRules]

    }
    const randomMemeRule = buildRandomMemeRule(keyMap)
    if (randomMemeRule) option.rule.push(randomMemeRule)
    Object.keys(keyMap).sort((a, b) => b.length - a.length).forEach(key => {
      let reg = forceSharp ? `^#${escapeRegExp(key)}` : `^#?${escapeRegExp(key)}`
      option.rule.push({
        /** 命令正则匹配 */
        reg,
        /** 执行方法 */
        fnc: 'memes'
      })
    })

    super(option)

    // generated by ChatGPT
    function generateCronExpression() {
      // 生成每天的半夜2-4点之间的小时值（随机选择）
      const hour = Math.floor(Math.random() * 3) + 2

      // 生成每小时的随机分钟值（0到59之间的随机数）
      const minute = Math.floor(Math.random() * 60)

      // 构建 cron 表达式
      return `${minute} ${hour} * * *`
    }

    this.task = {
      // 每天的凌晨3点执行
      cron: generateCronExpression(),
      name: 'memes自动更新任务',
      fnc: () => this.init(true)
    }
  }

  async init(forceRefresh = false) {
    mkdirs(memeDataDir)
    infos = readJsonObject(path.join(memeDataDir, 'infos.json'))
    keyMap = readJsonObject(path.join(memeDataDir, 'keyMap.json'))

    let remoteInfosLoaded = false
    let remoteKeyMapLoaded = false

    if (forceRefresh || !isNonEmptyObject(infos) || !isNonEmptyObject(keyMap)) {
      logger.mark(`yunzai-meme 正在${forceRefresh ? '刷新' : '拉取'}远程元数据`)
      try {
        const [remoteInfos, remoteKeyMap] = await Promise.all([
          fetchJson(`${baseUrl}/memes/static/infos.json`),
          fetchJson(`${baseUrl}/memes/static/keyMap.json`)
        ])
        if (!isNonEmptyObject(remoteInfos)) throw new Error('infos.json 内容为空')
        if (!isNonEmptyObject(remoteKeyMap)) throw new Error('keyMap.json 内容为空')
        infos = remoteInfos
        keyMap = remoteKeyMap
        remoteInfosLoaded = true
        remoteKeyMapLoaded = true
        await Promise.all([
          writeJsonAtomic(path.join(memeDataDir, 'infos.json'), infos),
          writeJsonAtomic(path.join(memeDataDir, 'keyMap.json'), keyMap)
        ])
      } catch (error) {
        logger.error(`yunzai-meme 元数据更新失败，继续使用本地缓存：${error.message}`)
      }
    }

    if (!isNonEmptyObject(infos) || !isNonEmptyObject(keyMap)) {
      logger.warn('静态元数据不可用，正在通过 info 接口重建索引')
      const keys = await fetchJson(`${baseUrl}/memes/keys`)
      if (!Array.isArray(keys) || keys.length === 0) {
        throw new Error('无法获取 meme key 列表')
      }

      const infoEntries = await mapWithConcurrency(keys, 8, async key => {
        try {
          const info = await fetchJson(`${baseUrl}/memes/${key}/info`)
          return [key, info]
        } catch (error) {
          logger.error(`获取 ${key} 详情失败：${error.message}`)
          return null
        }
      })

      const rebuiltInfos = {}
      const rebuiltKeyMap = {}
      for (const entry of infoEntries.filter(Boolean)) {
        const [key, info] = entry
        if (!info || !Array.isArray(info.keywords)) continue
        rebuiltInfos[key] = info
        for (const keyword of info.keywords) rebuiltKeyMap[keyword] = key
      }

      if (!isNonEmptyObject(rebuiltInfos) || !isNonEmptyObject(rebuiltKeyMap)) {
        throw new Error('重建 meme 元数据失败')
      }
      infos = rebuiltInfos
      keyMap = rebuiltKeyMap
      await Promise.all([
        writeJsonAtomic(path.join(memeDataDir, 'infos.json'), infos),
        writeJsonAtomic(path.join(memeDataDir, 'keyMap.json'), keyMap)
      ])
      remoteInfosLoaded = true
      remoteKeyMapLoaded = true
    }

    const memeRules = Object.keys(keyMap)
      .sort((a, b) => b.length - a.length)
      .map(key => ({
        reg: forceSharp ? `^#${escapeRegExp(key)}` : `^#?${escapeRegExp(key)}`,
        fnc: 'memes'
      }))
    const randomMemeRule = buildRandomMemeRule(keyMap)
    this.rule = [...commandRules, ...(randomMemeRule ? [randomMemeRule] : []), ...memeRules]

    const refreshed = remoteInfosLoaded && remoteKeyMapLoaded
    if (refreshed) clearListCacheFiles()
    return { refreshed }
  }

  async memesUpdate(e) {
    await e.reply('yunzai-memes更新中')
    try {
      const { refreshed } = await this.init(true)
      if (!refreshed) {
        await e.reply('远程资源暂时不可用，已继续使用本地缓存')
        return true
      }
    } catch (err) {
      await e.reply('更新失败：' + err.message)
      return true
    }
    await e.reply('更新完成')
    return true
  }

  async memesHelp(e) {
    await e.reply('【memes列表】：每页200个，使用合并转发查看全部列表\n【memes列表 2】：只查看第2页\n【{表情名称}】：根据文字或图片制作表情包\n【随机meme】：随机制作一些表情包\n【随机+表情名称】：按图片需求随机抽取群友，如「随机锤」「随机撅」\n【随机meme+表情名称】：无歧义写法，如「随机meme 咖波捶打」\n【meme搜索+关键词】：搜索表情包关键词\n【{表情名称}+详情】：查看该表情所支持的参数')
    return true
  }

  async memesSearch(e) {
    let search = e.msg.replace(/^#?(meme(s)?|表情包)搜索/, '').trim()
    if (!search) {
      await e.reply('你要搜什么？')
      return true
    }
    let hits = Object.keys(keyMap).filter(k => k.indexOf(search) > -1)
    let result = '搜索结果'
    if (hits.length > 0) {
      for (let i = 0; i < hits.length; i++) {
        result += `\n${i + 1}. ${hits[i]}`
      }
    } else {
      result += '\n无'
    }
    await e.reply(result, e.isGroup)
    return true
  }

  async memesList(e) {
    try {
      const memeKeys = Object.keys(infos)
        .filter(key => infos[key]?.params_type)
        .sort((a, b) => {
          const nameA = infos[a]?.keywords?.[0] || a
          const nameB = infos[b]?.keywords?.[0] || b
          return nameA.localeCompare(nameB, 'zh-CN')
        })

      if (memeKeys.length === 0) {
        await e.reply('meme 数据尚未加载，请先发送「meme更新」', true)
        return true
      }

      const pageMatch = e.msg.match(/列表\s*(\d+)?$/)
      const requestedPage = pageMatch?.[1] ? Number(pageMatch[1]) : null
      // 服务端构建镜像时已预渲染的列表优先使用（GET /memes/static/list/manifest.json），
      // meme 集合或页大小不一致时自动回退到实时渲染。
      const staticList = resolveStaticList(await fetchStaticListManifest(), memeKeys, listPageSize)
      if (staticList) logger.debug(`使用静态 meme 列表 version=${staticList.version} pages=${staticList.pages.length}`)
      const totalPages = staticList ? staticList.pages.length : Math.ceil(memeKeys.length / listPageSize)
      if (requestedPage !== null && (!Number.isInteger(requestedPage) || requestedPage < 1 || requestedPage > totalPages)) {
        await e.reply(`页码无效，当前共有 ${totalPages} 页`, true)
        return true
      }

      const listVersion = buildListVersion(memeKeys)
      const cacheTag = staticList ? `static${staticList.version}_${listVersion}` : listVersion
      clearListCacheFiles(cacheTag)
      const pages = requestedPage === null
        ? Array.from({ length: totalPages }, (_, index) => index + 1)
        : [requestedPage]

      if (pages.length > 1) {
        await e.reply(`正在准备 ${memeKeys.length} 个 meme，共 ${totalPages} 页，请稍候……`)
      }

      const forwardNodes = []
      for (const page of pages) {
        const start = (page - 1) * listPageSize
        const staticPage = staticList ? staticList.pages[page - 1] : null
        const pageKeys = staticPage ? staticPage.keys : memeKeys.slice(start, start + listPageSize)
        try {
          const resultFileLoc = await getMemeListPage(
            pageKeys,
            page,
            cacheTag,
            staticPage ? { url: `${baseUrl}/memes/static/list/${staticPage.file}` } : null
          )
          forwardNodes.push(makeForwardNode(
            e,
            `meme 列表第 ${page}/${totalPages} 页（${start + 1}-${start + pageKeys.length}，共 ${memeKeys.length} 个）`,
            segment.image(path.resolve(resultFileLoc))
          ))
        } catch (error) {
          logger.error(`meme 列表第 ${page} 页生成失败：${error.message}`)
          forwardNodes.push(makeForwardNode(
            e,
            `meme 列表第 ${page}/${totalPages} 页生成失败：${error.message}`
          ))
        }
      }

      await sendForwardNodes(e, forwardNodes)
      return true
    } catch (error) {
      console.error('memesList error:', error)
      await e.reply('获取表情包列表失败：' + error.message, true)
      return true
    }
  }

  /**
   * @description: 
   * @param {*} e
   * @return {*}
   */
  async randomMemes(e) {
    let keys = Object.keys(infos).filter(key => infos[key]?.params_type?.min_images === 1 && infos[key]?.params_type?.min_texts === 0)
    if (keys.length === 0) {
      await e.reply('当前没有可用于随机生成的 meme', true)
      return true
    }
    let index = _.random(0, keys.length - 1, false)
    logger.debug(keys, index)
    e.msg = infos[keys[index]].keywords[0]
    return await this.memes(e)
  }

  /**
   * 随机抽取群友制作指定 meme，例如：#随机锤、#随机撅、#随机舰长
   * 图片数量固定时按固定数量抽取；图片数量为区间时，在区间内随机抽取。
   */
  async randomMeme(e) {
    if (!e.group || typeof e.group.getMemberMap !== 'function') {
      await e.reply('「随机+表情名称」只能在群聊中使用', true)
      return true
    }

    const inputTarget = e.msg
      .replace(/^#?随机\s*(?:(?:meme(?:s)?|表情包)\s+)?/, '')
      .trim()
    const target = randomMemeAliases[inputTarget] || inputTarget
    const targetCode = keyMap[target]
    const info = infos[targetCode]
    if (!target || !targetCode || !info) {
      await e.reply(`没有找到「${inputTarget || '该名称'}」对应的 meme，请发送「meme搜索+关键词」查询`, true)
      return true
    }

    const minImages = Number(info.params_type?.min_images) || 0
    const maxImages = Number(info.params_type?.max_images) || 0
    if (minImages < 1 || maxImages < 1) {
      await e.reply(`「${target}」不需要群友头像，无法使用随机群友模式`, true)
      return true
    }

    let memberMap
    try {
      memberMap = await e.group.getMemberMap()
    } catch (error) {
      logger.error(`获取群成员列表失败：${error.message}`)
      await e.reply('获取群成员列表失败，请稍后再试', true)
      return true
    }

    const members = getAvailableGroupMembers(memberMap, e)
    if (members.length < minImages) {
      await e.reply(`「${target}」至少需要 ${minImages} 名群友，当前只有 ${members.length} 名可选群友`, true)
      return true
    }

    const availableMaxImages = Math.min(Math.max(minImages, maxImages), members.length)
    const imageCount = _.random(minImages, availableMaxImages, false)
    const selectedMembers = _.sampleSize(members, imageCount)
    logger.debug(`随机 ${target}：抽取 ${imageCount} 名群友`, selectedMembers.map(member => member.userId))

    const originalEvent = {
      msg: e.msg,
      message: e.message,
      img: e.img,
      source: e.source,
      reply_id: e.reply_id
    }

    try {
      // 伪造成主动 @ 群友的调用，复用 memes() 已有的头像、昵称、性别及主人保护逻辑。
      e.msg = target
      e.message = selectedMembers.map(member => ({
        type: 'at',
        qq: member.userId,
        text: `@${member.name}`,
        gender: member.gender
      }))
      // 必须设为 undefined；空数组在 JS 中仍为真，会误入“随消息图片”分支而跳过 @ 头像。
      e.img = undefined
      // 即使用户回复某条消息发送随机命令，也应优先使用随机群友，而不是被回复消息里的图片。
      e.source = undefined
      e.reply_id = undefined
      await this.memes(e)
      return true
    } finally {
      Object.assign(e, originalEvent)
    }
  }

  /**
   * #memes
   * @param e oicq传递的事件参数e
   */
  async memes(e) {
    // console.log(e)
    let msg = e.msg.replace('#', '')
    /**
   * 智能匹配最长关键词
   * @param {string} msg 用户消息
   * @param {Object} keyMap 关键词映射对象
   * @returns {string} 匹配到的最长关键词，如果没有匹配则返回null
   */
    function findLongestMatchingKey(msg, keyMap) {
      // 找出所有匹配消息开头的关键词
      const matchingKeys = Object.keys(keyMap).filter(k => msg.startsWith(k));
      if (matchingKeys.length === 0) {
        return null; // 没有匹配项
      }
      // 按关键词长度降序排序，选择最长的一个
      return matchingKeys.sort((a, b) => b.length - a.length)[0];
    }
    // 替换原有的硬编码匹配逻辑
    let target = findLongestMatchingKey(msg, keyMap);

    let targetCode = keyMap[target]
    if (!target || !targetCode || !infos[targetCode]) {
      await e.reply('没有找到对应的 meme，请发送「meme搜索+关键词」查询', true)
      return true
    }
    // let target = e.msg.replace(/^#?meme(s)?/, '')
    let text1 = _.trimStart(e.msg, '#').replace(target, '')
    if (text1.trim() === '详情' || text1.trim() === '帮助') {
      await e.reply(detail(targetCode))
      return true
    }
    let [text, args = ''] = text1.split('#')
    let userInfos
    let formData = new FormData()
    let info = infos[targetCode]
    let fileLoc
    if (info.params_type.max_images > 0) {
      // 可以有图，来从回复、发送和头像找图
      let imgUrls = []
      if (e.source || e.reply_id) {
        // 优先从回复找图
        let reply
        if (this.e.getReply) {
          reply = await this.e.getReply()
        } else if (this.e.source) {
          if (this.e.group?.getChatHistory)
            reply = (await this.e.group.getChatHistory(this.e.source.seq, 1)).pop()
          else if (this.e.friend?.getChatHistory)
            reply = (await this.e.friend.getChatHistory(this.e.source.time, 1)).pop()
        }
        if (reply?.message) {
          for (let val of reply.message) {
            if (val.type === 'image') {
              console.log(val)
              imgUrls.push(val.url)
            }
          }
        }
      } else if (e.img) {
        // 一起发的图
        imgUrls.push(...e.img)
      } else if (e.message.filter(m => m.type === 'at').length > 0) {
        // 艾特的用户的头像
        let ats = e.message.filter(m => m.type === 'at')
        imgUrls = ats.map(at => at.qq).map(qq => `https://q1.qlogo.cn/g?b=qq&s=160&nk=${qq}`)
      }
      if (!imgUrls || imgUrls.length === 0) {
        // 如果都没有，用发送者的头像
        imgUrls = [await getAvatar(e)]
      }
      if (imgUrls.length < info.params_type.min_images && imgUrls.indexOf(await getAvatar(e)) === -1) {
        // 如果数量不够，补上发送者头像，且放到最前面
        let me = [await getAvatar(e)]

        imgUrls = me.concat(imgUrls)
        // imgUrls.push(`https://q1.qlogo.cn/g?b=qq&s=160&nk=${e.msg.sender.user_id}`)
      }
      logger.debug('imgUrls:', imgUrls)
      if (protectList.includes(targetCode) && masterProtectDo) {
        let me = [await getAvatar(e)]
        let masters = await getMasterQQ()
        // 有些meme只需要传一张图，此时如果targetQQ是主人，那meme的人就是他自己
        if (imgUrls.length === 1) {
          if (imgUrls[0].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[0].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls[0] = me[0]
            }
          }
        } else {
          if (imgUrls[1].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[1].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls = [imgUrls[1]].concat(me)
            }
          }
        }
      }
      imgUrls = imgUrls.slice(0, Math.min(info.params_type.max_images, imgUrls.length))
      for (let i = 0; i < imgUrls.length; i++) {
        let imgUrl = imgUrls[i]
        const imageResponse = await fetch(imgUrl)
        const blob = await imageResponse.blob()
        const arrayBuffer = await blob.arrayBuffer()
        const buffer = Buffer.from(arrayBuffer)
        formData.append('images', new File([buffer], `avatar_${i}.jpg`, { type: 'image/jpeg' }))
      }
    }
    if (text && info.params_type.max_texts === 0) {
      return false
    }
    if (!text && info.params_type.min_texts > 0) {
      if (e.message.filter(m => m.type === 'at').length > 0) {
        text = _.trim(e.message.filter(m => m.type === 'at')[0].text, '@')
      } else {
        text = e.sender.card || e.sender.nickname
      }
    }
    let texts = text.split('/', info.params_type.max_texts)
    if (texts.length < info.params_type.min_texts) {
      await e.reply(`字不够！要至少${info.params_type.min_texts}个用/隔开！`, true)
      return true
    }
    texts.forEach(t => {
      formData.append('texts', t)
    })
    if (info.params_type.max_texts > 0 && formData.getAll('texts').length === 0) {
      if (formData.getAll('texts').length < info.params_type.max_texts) {
        if (e.message.filter(m => m.type === 'at').length > 0) {
          formData.append('texts', _.trim(e.message.filter(m => m.type === 'at')[0].text, '@'))
        } else {
          formData.append('texts', e.sender.card || e.sender.nickname)
        }
      }
    }
    if (e.message.filter(m => m.type === 'at').length > 0) {
      userInfos = e.message.filter(m => m.type === 'at')
      let mm = await e.group.getMemberMap()
      userInfos.forEach(ui => {
        let user = mm.get(ui.qq)
        if (user) {
          ui.gender = user.sex
          ui.text = user.card || user.nickname
        }
      })
    }
    if (!userInfos) {
      userInfos = [{ text: e.sender.card || e.sender.nickname, gender: e.sender.sex }]
    }
    args = handleArgs(targetCode, args, userInfos)
    if (args) {
      formData.set('args', args)
    }
    const images = formData.getAll('images')
    if (checkFileSize(images)) {
      return this.e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
    }
    console.log('input', { target, targetCode, images, texts: formData.getAll('texts'), args: formData.getAll('args') })
    let response = await fetch(baseUrl + '/memes/' + targetCode + '/', {
      method: 'POST',
      body: formData
      // headers: {
      // 'Content-Type': 'multipart/form-data'
      // }
    })
    // console.log(response.status)
    if (response.status > 299) {
      let error = await response.text()
      console.error(error)
      await e.reply(error, true)
      return true
    }
    const resultBlob = await response.blob()
    const resultArrayBuffer = await resultBlob.arrayBuffer()
    
    // 检查响应是否为空
    if (resultArrayBuffer.byteLength === 0) {
      console.error('API returned empty response for meme:', targetCode)
      await e.reply('表情包生成失败：服务器返回了空响应', true)
      return true
    }
    
    const resultBase64 = Buffer.from(resultArrayBuffer).toString('base64')
    await e.reply(segment.image("base64://" + resultBase64), reply)
  }
}

function makeForwardNode(e, text, image = null) {
  const bot = e.bot || global.Bot || {}
  const userId = Number(e.self_id || bot.uin || bot.user_id || e.user_id || 10000)
  const nickname = bot.nickname || bot.info?.nickname || 'meme列表'
  return {
    user_id: userId,
    nickname,
    message: image ? [text, image] : text
  }
}

async function sendForwardNodes(e, nodes) {
  const target = e.group || e.friend
  const bot = e.bot || global.Bot
  try {
    let forwardMessage
    if (typeof target?.makeForwardMsg === 'function') {
      forwardMessage = await target.makeForwardMsg(nodes)
    } else if (typeof bot?.makeForwardMsg === 'function') {
      forwardMessage = await bot.makeForwardMsg(nodes)
    } else {
      throw new Error('当前适配器不支持合并转发接口')
    }
    await e.reply(forwardMessage)
  } catch (error) {
    logger.warn(`合并转发发送失败，改为逐页发送：${error.message}`)
    for (const node of nodes) await e.reply(node.message)
  }
}

function isNonEmptyObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length > 0
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function buildRandomMemeRule(keywordMap) {
  const keywords = new Set(Object.keys(keywordMap || {}))
  for (const [alias, target] of Object.entries(randomMemeAliases)) {
    if (keywordMap?.[target]) keywords.add(alias)
  }
  if (keywords.size === 0) return null

  const alternatives = [...keywords]
    .sort((a, b) => b.length - a.length)
    .map(escapeRegExp)
    .join('|')
  const sharpPrefix = forceSharp ? '#' : '#?'
  return {
    reg: `^${sharpPrefix}随机\\s*(?:${alternatives})\\s*$`,
    fnc: 'randomMeme'
  }
}

function getAvailableGroupMembers(memberMap, e) {
  let entries = []
  if (Array.isArray(memberMap)) {
    entries = memberMap.map((member, index) => [member?.user_id ?? member?.qq ?? index, member])
  } else if (memberMap instanceof Map || typeof memberMap?.entries === 'function') {
    entries = [...memberMap.entries()]
  } else if (memberMap && typeof memberMap === 'object') {
    entries = Object.entries(memberMap)
  }

  const botIds = new Set([
    e.self_id,
    e.bot?.uin,
    e.bot?.user_id,
    global.Bot?.uin,
    global.Bot?.user_id
  ].filter(id => id !== undefined && id !== null).map(String))
  const seen = new Set()

  return entries.map(([mapKey, memberValue]) => {
    const member = memberValue || {}
    const userId = member.user_id ?? member.userId ?? member.qq ?? mapKey
    return {
      userId,
      name: member.card || member.nickname || member.nick || String(userId),
      gender: member.sex || member.gender || 'unknown'
    }
  }).filter(member => {
    const userId = String(member.userId ?? '')
    if (!/^\d+$/.test(userId) || userId === '0' || botIds.has(userId) || seen.has(userId)) return false
    seen.add(userId)
    return true
  })
}

function readJsonObject(file) {
  if (!fs.existsSync(file)) return {}
  try {
    const content = fs.readFileSync(file, 'utf8')
    if (!content.trim()) throw new Error('文件为空')
    const parsed = JSON.parse(content)
    if (!isNonEmptyObject(parsed)) throw new Error('内容不是非空对象')
    return parsed
  } catch (error) {
    logger.error(`忽略损坏的缓存文件 ${file}：${error.message}`)
    try {
      fs.unlinkSync(file)
    } catch {}
    return {}
  }
}

async function writeJsonAtomic(file, value) {
  const tempFile = `${file}.tmp-${process.pid}-${Date.now()}`
  try {
    await fs.promises.writeFile(tempFile, JSON.stringify(value))
    await fs.promises.rename(tempFile, file)
  } finally {
    try {
      await fs.promises.unlink(tempFile)
    } catch {}
  }
}

async function fetchJson(url, timeoutMs = 60000) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const response = await fetch(url, { signal: controller.signal })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    return await response.json()
  } finally {
    clearTimeout(timer)
  }
}

async function mapWithConcurrency(items, concurrency, mapper) {
  const results = new Array(items.length)
  let nextIndex = 0
  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (nextIndex < items.length) {
      const index = nextIndex++
      results[index] = await mapper(items[index], index)
    }
  })
  await Promise.all(workers)
  return results
}

function buildListVersion(memeKeys) {
  const fingerprint = {
    pageSize: listPageSize,
    memes: memeKeys.map(key => ({
      key,
      keywords: infos[key]?.keywords || [],
      modified: infos[key]?.date_modified || ''
    }))
  }
  return createHash('sha256').update(JSON.stringify(fingerprint)).digest('hex').slice(0, 12)
}

function detectImageExtension(buffer) {
  if (buffer.length >= 8 && buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return 'png'
  if (buffer.length >= 3 && buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) return 'jpg'
  if (buffer.length >= 6 && ['GIF87a', 'GIF89a'].includes(buffer.subarray(0, 6).toString('ascii'))) return 'gif'
  if (buffer.length >= 12 && buffer.subarray(0, 4).toString('ascii') === 'RIFF' && buffer.subarray(8, 12).toString('ascii') === 'WEBP') return 'webp'
  return null
}

function isValidImageFile(file) {
  try {
    const stat = fs.statSync(file)
    if (!stat.isFile() || stat.size < minimumImageBytes) return false
    const fd = fs.openSync(file, 'r')
    try {
      const header = Buffer.alloc(16)
      const bytesRead = fs.readSync(fd, header, 0, header.length, 0)
      return Boolean(detectImageExtension(header.subarray(0, bytesRead)))
    } finally {
      fs.closeSync(fd)
    }
  } catch {
    return false
  }
}

function clearListCacheFiles(activeVersion = '') {
  if (!fs.existsSync(memeDataDir)) return
  const activePrefix = activeVersion ? `render_list_v${listCacheVersion}_${activeVersion}_` : ''
  for (const filename of fs.readdirSync(memeDataDir)) {
    if (filename.startsWith('.render-list-')) {
      const file = path.join(memeDataDir, filename)
      try {
        if (Date.now() - fs.statSync(file).mtimeMs > 10 * 60 * 1000) fs.unlinkSync(file)
      } catch {}
      continue
    }
    if (!filename.startsWith('render_list')) continue
    if (activePrefix && filename.startsWith(activePrefix)) continue
    try {
      fs.unlinkSync(path.join(memeDataDir, filename))
    } catch (error) {
      logger.warn(`清理旧列表缓存失败 ${filename}：${error.message}`)
    }
  }
}

function findValidListCache(cacheBase) {
  for (const extension of ['png', 'jpg', 'gif', 'webp']) {
    const file = `${cacheBase}.${extension}`
    if (!fs.existsSync(file)) continue
    if (isValidImageFile(file)) return file
    try {
      fs.unlinkSync(file)
    } catch {}
  }
  return null
}

/**
 * 取回列表页图片：优先使用服务端预渲染的静态地址，不可用时回退到实时渲染接口。
 * @param {string[]} pageKeys 该页的 meme key（回退实时渲染时使用）
 * @param {number} page 页码
 * @param {string} cacheTag 缓存标识（使用静态列表时含其版本号，便于换版后失效）
 * @param {{url: string}|null} staticSource 静态图片地址
 */
async function getMemeListPage(pageKeys, page, cacheTag, staticSource = null) {
  const cacheBase = path.join(memeDataDir, `render_list_v${listCacheVersion}_${cacheTag}_p${page}`)
  const cachedFile = findValidListCache(cacheBase)
  if (cachedFile) return cachedFile

  if (listRenderTasks.has(cacheBase)) return await listRenderTasks.get(cacheBase)

  const renderTask = (async () => {
    let tempFile = ''
    try {
      let resultBuffer = staticSource?.url ? await fetchStaticListImage(staticSource.url) : null
      if (!resultBuffer) resultBuffer = await renderMemeListPage(pageKeys)

      const extension = detectImageExtension(resultBuffer)
      if (resultBuffer.length < minimumImageBytes || !extension) {
        throw new Error(`列表服务返回的不是有效图片（${resultBuffer.length} bytes）`)
      }

      const finalFile = `${cacheBase}.${extension}`
      tempFile = path.join(memeDataDir, `.render-list-${process.pid}-${Date.now()}.tmp`)
      await fs.promises.writeFile(tempFile, resultBuffer)
      await fs.promises.rename(tempFile, finalFile)
      tempFile = ''
      return finalFile
    } finally {
      if (tempFile) {
        try {
          await fs.promises.unlink(tempFile)
        } catch {}
      }
    }
  })()

  listRenderTasks.set(cacheBase, renderTask)
  try {
    return await renderTask
  } finally {
    listRenderTasks.delete(cacheBase)
  }
}

/**
 * 拉取服务端构建镜像时生成的静态列表清单（含每页 meme key）。
 * @returns {Promise<object|null>}
 */
async function fetchStaticListManifest() {
  if (!staticListEnabled) return null
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), staticListManifestTimeout)
  try {
    const response = await fetch(`${baseUrl}/memes/static/list/manifest.json`, { signal: controller.signal })
    if (!response.ok) {
      logger.debug(`静态 meme 列表清单不可用（HTTP ${response.status}），回退到实时渲染`)
      return null
    }
    const manifest = await response.json()
    if (!manifest || !Array.isArray(manifest.pages) || manifest.pages.length === 0) return null
    return manifest
  } catch (error) {
    logger.warn(`静态 meme 列表清单获取失败，回退到实时渲染：${error.message}`)
    return null
  } finally {
    clearTimeout(timer)
  }
}

/**
 * 校验静态列表是否与本地 meme 数据一致（页大小相同且全部 key 一一对应）。
 * 不一致时返回 null，调用方回退到 POST /memes/render_list。
 * @param {object|null} manifest
 * @param {string[]} memeKeys 本地（实时接口）给出的 meme key 列表
 * @param {number} pageSize 本地分页大小
 * @returns {{version: string, pages: Array<{page: number, file: string, keys: string[]}>}|null}
 */
function resolveStaticList(manifest, memeKeys, pageSize) {
  if (!manifest) return null
  if (Number(manifest.pageSize) !== pageSize) {
    logger.debug(`静态 meme 列表页大小不匹配（${manifest.pageSize} != ${pageSize}），回退到实时渲染`)
    return null
  }
  const pages = (manifest.pages || [])
    .map(page => ({
      page: Number(page?.page),
      file: safeStaticPageFile(page),
      keys: Array.isArray(page?.keys) ? page.keys.filter(key => typeof key === 'string') : []
    }))
    .filter(page => Number.isInteger(page.page) && page.file && page.keys.length > 0)
    .sort((a, b) => a.page - b.page)
  if (pages.length === 0) return null

  const flat = pages.flatMap(page => page.keys)
  if (flat.length !== memeKeys.length) {
    logger.debug(`静态 meme 列表数量不匹配（${flat.length} != ${memeKeys.length}），回退到实时渲染`)
    return null
  }
  const expected = new Set(memeKeys)
  if (flat.length !== expected.size || flat.some(key => !expected.has(key))) {
    logger.debug('静态 meme 列表内容与当前 meme 数据不一致，回退到实时渲染')
    return null
  }

  return {
    version: String(manifest.version || manifest.signature || 'na').slice(0, 12),
    pages
  }
}

function safeStaticPageFile(page) {
  const name = typeof page?.file === 'string' ? page.file.split('/').pop() : ''
  return /^[A-Za-z0-9._-]+\.(png|jpe?g|gif|webp)$/i.test(name) ? name : ''
}

/**
 * 下载服务端预渲染的列表图片，失败返回 null（由调用方回退）。
 * @returns {Promise<Buffer|null>}
 */
async function fetchStaticListImage(url) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), staticListImageTimeout)
  try {
    const response = await fetch(url, { signal: controller.signal })
    if (!response.ok) {
      logger.warn(`静态 meme 列表图片获取失败（HTTP ${response.status}）：${url}`)
      return null
    }
    const buffer = Buffer.from(await response.arrayBuffer())
    if (buffer.length < minimumImageBytes || !detectImageExtension(buffer)) {
      logger.warn(`静态 meme 列表图片无效（${buffer.length} bytes）：${url}`)
      return null
    }
    return buffer
  } catch (error) {
    logger.warn(`静态 meme 列表图片获取失败：${error.message}`)
    return null
  } finally {
    clearTimeout(timer)
  }
}

/**
 * 回退路径：请求服务端实时渲染该页列表图片。
 * @param {string[]} pageKeys
 * @returns {Promise<Buffer>}
 */
async function renderMemeListPage(pageKeys) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 180000)
  try {
    const response = await fetch(`${baseUrl}/memes/render_list`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        meme_list: pageKeys.map(memeKey => ({ meme_key: memeKey, disabled: false, labels: [] })),
        text_template: '{index}. {keywords}',
        add_category_icon: true
      }),
      signal: controller.signal
    })
    if (!response.ok) throw new Error(`列表服务返回 HTTP ${response.status}`)
    return Buffer.from(await response.arrayBuffer())
  } finally {
    clearTimeout(timer)
  }
}

function handleArgs(key, args, userInfos) {
  if (!args) {
    args = ''
  }

  let argsObj = {}

  // 检查是否有参数类型定义
  if (infos[key]?.params_type?.args_type) {
    const argsType = infos[key].params_type.args_type;
    const argsModel = argsType.args_model;
    const parserOptions = argsType.parser_options || [];

    // 处理枚举类型参数
    for (const prop in argsModel.properties) {
      if (prop === 'user_infos') continue; // 用户信息单独处理

      const propInfo = argsModel.properties[prop];

      // 查找相关的parser选项
      const relatedOptions = parserOptions.filter(opt =>
        opt.dest === prop ||
        (opt.args && opt.args.some(arg => arg.name === prop))
      );

      if (propInfo.enum && relatedOptions.length > 0) {
        // 为枚举类型创建映射表
        const valueMap = {};

        // 从parser options中提取名称映射
        relatedOptions.forEach(opt => {
          if (opt.action?.type === 0) {
            opt.names.forEach(name => {
              // 处理非选项形式(如"左", "右")和选项形式(如"--right")
              if (!/^-/.test(name)) {
                valueMap[name] = opt.action.value;
              } else if (name.startsWith('--')) {
                // 处理选项形式，去掉前缀--
                const simpleName = name.substring(2);
                valueMap[simpleName] = opt.action.value;
              }
            });
          }
        });

        // 设置默认值
        const trimmedArg = args.trim();
        argsObj[prop] = valueMap[trimmedArg] || propInfo.default;
      }
      // 处理数字类型参数
      else if (propInfo.type === 'integer' || propInfo.type === 'number') {
        const trimmedArg = args.trim();
        // 尝试将参数解析为数字
        if (/^\d+$/.test(trimmedArg)) {
          const numValue = parseInt(trimmedArg);
          argsObj[prop] = numValue;
        }
      }
    }
  }

  argsObj.user_infos = userInfos.map(u => {
    return {
      name: _.trim(u.text, '@'),
      gender: u.gender || 'unknown'
    }
  })

  return JSON.stringify(argsObj);
}

const detail = code => {
  let d = infos[code];
  let keywords = d.keywords.join('、');
  let ins = `【代码】${d.key}\n【名称】${keywords}\n【最大图片数量】${d.params_type.max_images}\n【最小图片数量】${d.params_type.min_images}\n【最大文本数量】${d.params_type.max_texts}\n【最小文本数量】${d.params_type.min_texts}\n【默认文本】${d.params_type.default_texts.join('/')}\n`;

  // 检查是否有参数类型定义
  if (d.params_type.args_type?.parser_options?.length > 0) {
    let supportArgs = generateSupportArgsText(d);
    ins += `【支持参数】${supportArgs}`;
  }

  return ins;
};

// 辅助函数：根据infos生成参数说明文本
function generateSupportArgsText(info) {
  try {
    const argsType = info.params_type.args_type;
    const props = argsType.args_model.properties;
    const options = argsType.parser_options;

    // 寻找主要参数及其描述
    let mainParam = '';
    let description = '';

    for (const prop in props) {
      if (prop !== 'user_infos') {
        const propInfo = props[prop];
        mainParam = prop;

        // 寻找参数说明
        const option = options.find(opt =>
          opt.dest === prop ||
          (opt.args && opt.args.some(arg => arg.name === prop))
        );

        if (option?.help_text) {
          description = option.help_text;
        } else if (propInfo.description) {
          description = propInfo.description;
        }

        // 如果是枚举类型，列出可能的值
        if (propInfo.enum) {
          // 收集中文参数名称（非选项形式）
          const chineseNames = options
            .filter(opt => opt.action?.type === 0 && opt.action?.value && opt.dest === prop)
            .flatMap(opt => opt.names.filter(name => !/^-/.test(name)));

          // 收集英文参数名称（从选项形式提取）
          const englishNames = options
            .filter(opt => opt.action?.type === 0 && opt.action?.value && opt.dest === prop)
            .flatMap(opt => opt.names
              .filter(name => name.startsWith('--'))
              .map(name => name.substring(2))
            );

          // 合并中文和英文参数名称
          const valueNames = [...new Set([...chineseNames, ...englishNames])];

          if (valueNames.length > 0) {
            const valuesText = valueNames.join('、');
            // 优先使用中文名称作为示例
            const exampleName = chineseNames.length > 0 ? chineseNames[0] : valueNames[0];
            return `${description || prop}，可选值：${valuesText}。如#${exampleName}`;
          }
        }
        // 处理数字类型
        else if (propInfo.type === 'integer' || propInfo.type === 'number') {
          // 添加数字范围说明（如果有）
          let rangeText = '';
          if (propInfo.minimum !== undefined && propInfo.maximum !== undefined) {
            rangeText = `范围为${propInfo.minimum}~${propInfo.maximum}`;
          } else if (propInfo.description && propInfo.description.includes('范围')) {
            rangeText = propInfo.description;
          }

          return `${description || prop}${rangeText ? '，' + rangeText : ''}。如#1`;
        }

        break;
      }
    }

    return description || `${mainParam}参数`;

  } catch (e) {
    console.error(`生成参数说明出错: ${e.message}`);
    return '支持额外参数';
  }
}

// 最大支持的文件大小（字节）
const maxFileSizeByte = maxFileSize * 1024 * 1024

// 如果有任意一个文件大于 maxSize，则返回true
function checkFileSize(files) {
  let fileList = Array.isArray(files) ? files : [files]
  fileList = fileList.filter(file => !!(file?.size))
  if (fileList.length === 0) {
    return false
  }
  return fileList.some(file => file.size >= maxFileSizeByte)
}

function mkdirs(dirname) {
  if (fs.existsSync(dirname)) {
    return true
  } else {
    if (mkdirs(path.dirname(dirname))) {
      fs.mkdirSync(dirname)
      return true
    }
  }
}

async function getMasterQQ () {
  return (await import('../../lib/config/config.js')).default.masterQQ
}

async function getAvatar(e, userId = e.sender.user_id) {
  if (typeof e.getAvatarUrl === 'function') {
    return await e.getAvatarUrl(0)
  }
  return `https://q1.qlogo.cn/g?b=qq&s=0&nk=${userId}`
}
